---
# We use the base docker-compose.yml for testing so we avoid
# port-forwarding to avoid port collisions when same test suite
# is being run in parallel on the git runners
# But b/c we want port-forwarding in dev, add as override
version: '3.2'
services:
  web:
    # Don't put this in docker-compose.yml or you will encounter
    # https://gitlab.com/gitlab-org/gitlab-runner/issues/1682
    volumes:
      - ".:/opt/couyang/salsa"
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
