apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: helistrong-com-tls
spec:
  secretName: helistrong-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: helistrong.com
  dnsNames:
    - helistrong.com
    - www.helistrong.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - helistrong.com
          - www.helistrong.com
