"""Initial migration.

Revision ID: 39a9fea061b9
Revises: 
Create Date: 2020-03-15 19:03:20.003304

"""
import salsa
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a9fea061b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusion_set',
    sa.Column('id', salsa.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('usr', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exclusion_set')),
    sa.UniqueConstraint('name', name=op.f('uq_exclusion_set_name')),
    sa.UniqueConstraint('usr', name=op.f('uq_exclusion_set_usr'))
    )
    op.create_table('user_account',
    sa.Column('id', salsa.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hashed', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_user_account_email')),
    sa.UniqueConstraint('name', name=op.f('uq_user_account_name')),
    sa.UniqueConstraint('password_hashed', name=op.f('uq_user_account_password_hashed'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_account')
    op.drop_table('exclusion_set')
    # ### end Alembic commands ###
