"""Add complete purchase attributes

Revision ID: 566afb5b027d
Revises: 6cacd4db55b8
Create Date: 2020-06-27 22:08:10.202713

"""
import salsa
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566afb5b027d'
down_revision = '6cacd4db55b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('buyer_complete', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('purchase', sa.Column('seller_complete', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'seller_complete')
    op.drop_column('purchase', 'buyer_complete')
    # ### end Alembic commands ###
