"""Add purchase table

Revision ID: 9b576b94565d
Revises: a84ad858b65a
Create Date: 2020-05-24 21:06:50.554708

"""
import salsa
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b576b94565d'
down_revision = 'a84ad858b65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', salsa.db.types.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', salsa.db.types.GUID(), nullable=False),
    sa.Column('listing_id', salsa.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], name=op.f('fk_purchase_listing_id_listing')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_purchase_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    # ### end Alembic commands ###
