"""Add listing table

Revision ID: a84ad858b65a
Revises: 434a7905b168
Create Date: 2020-05-24 20:35:31.269876

"""
import salsa
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84ad858b65a'
down_revision = '434a7905b168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', salsa.db.types.GUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_available', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', salsa.db.types.GUID(), nullable=False),
    sa.Column('product_id', salsa.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_listing_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_listing_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing')
    # ### end Alembic commands ###
