"""Remove unique constraints on user_account table

Revision ID: e3a1fba5d24c
Revises: 48f175eabbe4
Create Date: 2020-03-15 20:54:25.427950

"""
import salsa
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a1fba5d24c'
down_revision = '48f175eabbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_account_email', 'user_account', type_='unique')
    op.drop_constraint('uq_user_account_name', 'user_account', type_='unique')
    op.drop_constraint('uq_user_account_password_hashed', 'user_account', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_account_password_hashed', 'user_account', ['password_hashed'])
    op.create_unique_constraint('uq_user_account_name', 'user_account', ['name'])
    op.create_unique_constraint('uq_user_account_email', 'user_account', ['email'])
    # ### end Alembic commands ###
