"""Add extradata field to user_account table

Revision ID: f91f0bbb43e5
Revises: 3c409a2d11f6
Create Date: 2020-05-31 05:01:33.388553

"""
import salsa
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91f0bbb43e5'
down_revision = '3c409a2d11f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('extradata', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'extradata')
    # ### end Alembic commands ###
